# Generated by Django 4.0.1 on 2022-01-18 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orchestry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Название оркестра')),
            ],
            options={
                'db_table': 'orchestry',
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('role', models.CharField(max_length=30, verbose_name='Роль в оркестре')),
                ('id_orkestry', models.ForeignKey(blank=True, db_column='id_orkestry', on_delete=django.db.models.deletion.DO_NOTHING, to='rk2_rest.orchestry')),
            ],
            options={
                'db_table': 'musician',
            },
        ),
    ]
