# Generated by Django 4.0.1 on 2022-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk2_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='role',
            field=models.CharField(max_length=32, verbose_name='Роль в оркестре'),
        ),
        migrations.AlterField(
            model_name='orchestry',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название оркестра'),
        ),
    ]
