# Generated by Django 4.0.1 on 2022-01-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rk2_rest', '0002_alter_musician_name_alter_musician_role_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='Musicians',
        ),
        migrations.RenameModel(
            old_name='Orchestry',
            new_name='Orchestrys',
        ),
    ]
