# Generated by Django 4.0.1 on 2022-01-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rk2_rest', '0003_rename_musician_musicians_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musicians',
        ),
        migrations.DeleteModel(
            name='Orchestrys',
        ),
    ]
