# Generated by Django 4.0.1 on 2022-01-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rk2_rest', '0004_delete_musicians_delete_orchestrys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orchestrys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Название оркестра')),
            ],
            options={
                'db_table': 'orchestry',
            },
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('role', models.CharField(max_length=32, verbose_name='Роль в оркестре')),
                ('id_orkestry', models.ForeignKey(blank=True, db_column='id_orkestry', on_delete=django.db.models.deletion.DO_NOTHING, to='rk2_rest.orchestrys')),
            ],
            options={
                'db_table': 'musician',
            },
        ),
    ]
